### ISSUE TITLE
Color coding the plotted channels

### ISSUE THREAD

**Issue by fanmingyu212** [HaeffnerLab/RealSimpleGrapher#16]
This could be done with an appropriately colored line next to the different data set names on the window on the left.

I will work on this if others think it is a good idea.

**Comment by aransfor** [comment]
I think this is a great idea, infact I have heard it tossed around by others

**Comment by aransfor** [comment]
@fanmingyu212 probably not possible but it would be cute if the check mark on the check box was the same color

**Comment by aransfor** [comment]
fixed with #19
